import { WebContainerCSS } from "@/components/common/WebContainer/WebContainerCSS";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <WebContainerCSS />
      </head>
      <body className={inter.className + " p-8"}>{children}</body>
    </html>
  );
}
